In [1]:
print(45)

45

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('doctor_availability.csv')
df.head(5)

,date_slot,specialization,doctor_name,is_available,patient_to_attend
0,05-08-2024 08:00,general_dentist,john doe,True,NaN
1,05-08-2024 08:30,general_dentist,john doe,False,1000082.0
2,05-08-2024 09:00,general_dentist,john doe,False,1000048.0
3,05-08-2024 09:30,general_dentist,john doe,False,1000036.0
4,05-08-2024 10:00,general_dentist,john doe,False,1000024.0

In [6]:
df["date_slot"] = df["date_slot"].str.replace("2024", "2026", regex=False)

In [7]:
df.head()

,date_slot,specialization,doctor_name,is_available,patient_to_attend
0,05-08-2026 08:00,general_dentist,john doe,True,NaN
1,05-08-2026 08:30,general_dentist,john doe,False,1000082.0
2,05-08-2026 09:00,general_dentist,john doe,False,1000048.0
3,05-08-2026 09:30,general_dentist,john doe,False,1000036.0
4,05-08-2026 10:00,general_dentist,john doe,False,1000024.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4280 entries, 0 to 4279
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date_slot          4280 non-null   object
 1   specialization     4280 non-null   object
 2   doctor_name        4280 non-null   object
 3   is_available       4280 non-null   bool
 4   patient_to_attend  1564 non-null   float64
dtypes: bool(1), float64(1), object(3)
memory usage: 138.1+ KB

In [8]:
sum(df['date_slot'].isnull())

0

In [9]:
print(df["date_slot"].head(10).tolist())

['05-08-2026 08:00', '05-08-2026 08:30', '05-08-2026 09:00', '05-08-2026 09:30', '05-08-2026 10:00', '05-08-2026 10:30', '05-08-2026 11:00', '05-08-2026 11:30', '05-08-2026 12:00', '05-08-2026 12:30']

In [10]:
df["patient_to_attend"] = df["patient_to_attend"].astype("Int64")

In [11]:
df['date_slot'].head()

0    05-08-2026 08:00
1    05-08-2026 08:30
2    05-08-2026 09:00
3    05-08-2026 09:30
4    05-08-2026 10:00
Name: date_slot, dtype: object

In [12]:
import pandas as pd

# Parse DD-MM-YYYY HH:MM
df["date_slot"] = pd.to_datetime(
    df["date_slot"],
    format="%d-%m-%Y %H:%M"
)

In [13]:
df['date_slot'].head()

0   2026-08-05 08:00:00
1   2026-08-05 08:30:00
2   2026-08-05 09:00:00
3   2026-08-05 09:30:00
4   2026-08-05 10:00:00
Name: date_slot, dtype: datetime64[ns]

In [77]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4280 entries, 0 to 4279
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date_slot          4280 non-null   datetime64[us]
 1   specialization     4280 non-null   str
 2   doctor_name        4280 non-null   str
 3   is_available       4280 non-null   bool
 4   patient_to_attend  1564 non-null   Int64
dtypes: Int64(1), bool(1), datetime64[us](1), str(2)
memory usage: 142.2 KB

In [15]:
df.isnull().sum()

date_slot               0
specialization          0
doctor_name             0
is_available            0
patient_to_attend    2716
dtype: int64

In [16]:
df.head()

,date_slot,specialization,doctor_name,is_available,patient_to_attend
0,2026-08-05 08:00:00,general_dentist,john doe,True,<NA>
1,2026-08-05 08:30:00,general_dentist,john doe,False,1000082
2,2026-08-05 09:00:00,general_dentist,john doe,False,1000048
3,2026-08-05 09:30:00,general_dentist,john doe,False,1000036
4,2026-08-05 10:00:00,general_dentist,john doe,False,1000024

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4280 entries, 0 to 4279
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date_slot          4280 non-null   datetime64[ns]
 1   specialization     4280 non-null   object
 2   doctor_name        4280 non-null   object
 3   is_available       4280 non-null   bool
 4   patient_to_attend  1564 non-null   Int64
dtypes: Int64(1), bool(1), datetime64[ns](1), object(2)
memory usage: 142.2+ KB

In [18]:
df.to_csv('doctor_availability_cleaned.csv', index=False)